### ISSUE TITLE
Fade-in doesn't work after failed "First aid" usage

### ISSUE THREAD

**Issue by Necrys** [alexbatalov/fallout1-ce#38] opened 2023-02-19 10:31 UTC
Steps:
1. Use First Aid skill on self

Screen fades out and never fades in if skill was failed. If it is successful it works ok.
Pressing F1 to call help dialog and pressing it again helps to bring it back.

System: PC, Win 10.
Build x64 from v1.0.0 tag
Game: Fallout 1, Steam release

**Comment by alexbatalov** [comment] 2023-02-20 10:49
Duplicate of #8, it's already been fixed.

**Closed by alexbatalov** 2023-02-20 10:49 UTC
